import type { Metadata } from "next";
import { QueryProvider } from "@/app/provider";
import { Toaster } from "sonner";
import "./globals.css";
export const metadata: Metadata = {
  title: "Nesteeq",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html>
      <body>
        <QueryProvider>{children}</QueryProvider>
        <Toaster richColors position="top-right" duration={3000}/>
      </body>
    </html>
  );
}
