export const ROLE = {
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
  PROPERTY_MANAGER: "PROPERTY_MANAGER",
  FACILITY_MANAGER: "FACILITY_MANAGER",
  TREASURER: "TREASURER",
  SECURITY_STAFF: "SECURITY_STAFF",
  RESIDENT: "RESIDENT",
  OWNER: "OWNER",
  TENANT: "TENANT",
  MAINTENANCE_STAFF: "MAINTENANCE_STAFF",
  MAINTENANCE_TECHNICIAN: "MAINTENANCE_TECHNICIAN",
  TECHNICIAN: "TECHNICIAN",
} as const;

export type Role = (typeof ROLE)[keyof typeof ROLE];

export const RESIDENT_ROLES = [ROLE.RESIDENT, ROLE.OWNER, ROLE.TENANT] as const;
export const MANAGEMENT_ROLES = [
  ROLE.ADMIN,
  ROLE.SUPER_ADMIN,
  ROLE.PROPERTY_MANAGER,
  ROLE.FACILITY_MANAGER,
] as const;
export const GLOBAL_ROLES = [ROLE.ADMIN, ROLE.SUPER_ADMIN] as const;
export const MAINTENANCE_ROLES = [
  ROLE.MAINTENANCE_STAFF,
  ROLE.MAINTENANCE_TECHNICIAN,
  ROLE.TECHNICIAN,
] as const;
export const TECHNICIAN_CREATOR_ROLES = [
  ROLE.ADMIN,
  ROLE.SUPER_ADMIN,
  ROLE.PROPERTY_MANAGER,
] as const;
export const APARTMENT_SCOPED_ALERT_ROLES = [
  ROLE.PROPERTY_MANAGER,
  ROLE.FACILITY_MANAGER,
  ROLE.TREASURER,
  ROLE.SECURITY_STAFF,
] as const;

export const RESIDENT_ROLE_SET = new Set<string>(RESIDENT_ROLES);
export const MANAGEMENT_ROLE_SET = new Set<string>(MANAGEMENT_ROLES);
export const GLOBAL_ROLE_SET = new Set<string>(GLOBAL_ROLES);
export const MAINTENANCE_ROLE_SET = new Set<string>(MAINTENANCE_ROLES);
export const TECHNICIAN_CREATOR_ROLE_SET = new Set<string>(TECHNICIAN_CREATOR_ROLES);
export const APARTMENT_SCOPED_ALERT_ROLE_SET = new Set<string>(APARTMENT_SCOPED_ALERT_ROLES);

const withRouteAliases = (roles: readonly string[]): readonly string[] =>
  Array.from(
    new Set(
      roles.flatMap((role) =>
        role.includes("_")
          ? [role, role.toLowerCase(), role.replace(/_/g, " ")]
          : [role, role.toLowerCase()]
      )
    )
  );

export const RESIDENT_ROUTE_ROLES = withRouteAliases(RESIDENT_ROLES);
export const MANAGEMENT_ROUTE_ROLES = withRouteAliases(MANAGEMENT_ROLES);
export const MAINTENANCE_ROUTE_ROLES = withRouteAliases(MAINTENANCE_ROLES);
export const TECHNICIAN_CREATOR_ROUTE_ROLES = withRouteAliases(TECHNICIAN_CREATOR_ROLES);

export const RESIDENT_AND_MANAGEMENT_ROUTE_ROLES = [
  ...RESIDENT_ROUTE_ROLES,
  ...MANAGEMENT_ROUTE_ROLES,
] as const;
export const MANAGEMENT_AND_MAINTENANCE_ROUTE_ROLES = [
  ...MANAGEMENT_ROUTE_ROLES,
  ...MAINTENANCE_ROUTE_ROLES,
] as const;
export const COMPLAINT_ACCESS_ROUTE_ROLES = [
  ...RESIDENT_ROUTE_ROLES,
  ...MANAGEMENT_ROUTE_ROLES,
  ...MAINTENANCE_ROUTE_ROLES,
] as const;
export const MAINTENANCE_ACCESS_ROUTE_ROLES = COMPLAINT_ACCESS_ROUTE_ROLES;
export const SCHEDULE_ACCESS_ROUTE_ROLES = MANAGEMENT_AND_MAINTENANCE_ROUTE_ROLES;
export const TECHNICIAN_ACCESS_ROUTE_ROLES = MANAGEMENT_AND_MAINTENANCE_ROUTE_ROLES;
export const FACILITY_DASHBOARD_ROUTE_ROLES = MANAGEMENT_ROUTE_ROLES;
export const REPORT_ROUTE_ROLES = MANAGEMENT_ROUTE_ROLES;
